apiVersion: v1
kind: Service
metadata:
    name: react-frontend-service
spec:
    ports:
        - port: 80
          nodePort: 30002
          protocol: TCP
    selector:
        appName: react-frontend-app # references the deployment-frontend.yml
    type: NodePort
