kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ .Values.kafka.deployment_name }}
spec:
    replicas: {{ .Values.kafka.replicas }}
    selector:
        matchLabels:
            app: {{ .Values.kafka.pod_label }}
            id: "{{ .Values.kafka.pod_id }}"
    template:
        metadata:
            labels:
                app: {{ .Values.kafka.pod_label }}
                id: "{{ .Values.kafka.pod_id }}"
        spec:
            containers:
                - name: {{ .Values.kafka.container_name }}
                  image: {{ .Values.kafka.image }}
                  ports:
                      - containerPort: {{ .Values.kafka.container_port }}
                  env:
                      - name: KAFKA_ADVERTISED_PORT
                        value: "{{ .Values.kafka.kafka_advertised_port }}"
                      - name: KAFKA_ADVERTISED_HOST_NAME
                        value: {{ .Values.kafka.kafka_advertised_host_name }}
                      - name: KAFKA_ZOOKEEPER_CONNECT
                        value: {{ .Values.kafka.kafka_zookeeper_connect }}
                      - name: KAFKA_BROKER_ID
                        value: "{{ .Values.kafka.kafka_broker_id }}"
                      - name: KAFKA_CREATE_TOPICS
                        value: {{ .Values.kafka.kafka_create_topics }}
