apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.kafka.service_name }}
spec:
    ports:
        - port: {{ .Values.kafka.container_port }}
          name: kafka-port
          protocol: TCP
    selector:
        app: {{ .Values.kafka.pod_label }}
        id: "{{ .Values.kafka.pod_id }}"
    type: LoadBalancer
