apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.dop_client_react.deployment_name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            appName: {{ .Values.dop_client_react.pod_label }}
    template:
        metadata:
            labels:
                appName: {{ .Values.dop_client_react.pod_label }}
                date: "{{ now | unixEpoch }}" # we force helm to think of this as a new yaml, and therefore force it to re-pull the latest image
        spec:
            containers:
                - name: {{ .Values.dop_client_react.container_name }}
                  image: {{ .Values.dop_client_react.image }}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: {{ .Values.dop_client_react.container_port }}
                  env:
                      - name: REACT_APP_BACKEND_BASE_URL
                        value: {{ .Values.dop_client_react.react_app_backend_base_url }}
                      - name: REACT_APP_SOCKET_BASE_URL
                        value: {{ .Values.dop_client_react.react_app_socket_base_url }}
