apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.dop_microservice.service_name }}
spec:
    ports:
        - port: {{ .Values.dop_microservice.container_port }}
          nodePort: {{ .Values.dop_microservice.node_port }}
          protocol: TCP
    selector:
        appName: {{ .Values.dop_microservice.pod_label }}
    type: NodePort
