apiVersion: v1
kind: Service
metadata:
    name: dop-client-react-service
spec:
    ports:
        - port: 80
          nodePort: 30001 # open the browser at http://localhost:30001/
          protocol: TCP
    selector:
        appName: dop-client-react # references the deployment-frontend.yml
    type: NodePort
