apiVersion: apps/v1
kind: Deployment
metadata:
    name: dop-server-flask-deployment
    labels:
        environment: production
    annotations:
        imageregistry: "https://hub.docker.com/"
spec:
    replicas: 1
    selector:
        matchLabels:
            appName: dop-server-flask
    template:
        metadata:
            labels:
                appName: dop-server-flask
        spec:
            containers:
                - name: dop-server-flask-container
                  image: ryanang/dop_server_flask:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8000
                  env:
                      - name: GRPC_HOST
                        value: "dop-microservice-service" # defined in dop_microservice/service.yml
                      - name: KAFKA_HOST
                        value: "kafka-service" # defined in kafka/kafka-service.yml
