# This is for local kubernetes cluster

dop_client_react:
    container_name: dop-client-react-container
    deployment_name: dop-client-react-deployment
    pod_label: dop-client-react
    image: ryanang/dop_client_react:latest # image on Docker Hub
    container_port: 80 # exposed port in Dockerfile
    node_port: 30001 # localhost port
    react_app_backend_base_url: http://192.168.64.2:30002/api
    react_app_socket_base_url: http://192.168.64.2:30002/
    
    service_name: dop-client-react-service

dop_microservice:
    container_name: dop-microservice-container
    deployment_name: dop-microservice-deployment
    pod_label: dop-microservice
    image: ryanang/dop_microservice:latest # image on Docker Hub
    container_port: 50051 # exposed port in Dockerfile
    node_port: 30003 # localhost port

    service_name: dop-microservice-service

dop_server_flask:
    container_name: dop-server-flask-container
    deployment_name: dop-server-flask-deployment
    pod_label: dop-server-flask
    image: ryanang/dop_server_flask:latest # image on Docker Hub
    container_port: 8000 # exposed port in Dockerfile
    node_port: 30002 # localhost port
    grpc_host: dop-microservice-service # dop_microservice's service name
    kafka_host: kafka-service
    mysql_host: dop-database.cvsrbibageju.ap-southeast-1.rds.amazonaws.com
    mysql_user: admin
    mysql_password: dopdatabaseroot
    mysql_database: dop_database
    
    service_name: dop-server-flask-service

dop_kafka_consumer:
    container_name: dop-kafka-consumer-container
    deployment_name: dop-kafka-consumer-deployment
    pod_label: dop-kafka-consumer
    image: ryanang/dop_kafka_consumer:latest # image on Docker Hub
    kafka_host: kafka-service
    service_name: dop-kafka-consumer-service

kafka:
    container_name: kafka-pod
    deployment_name: kafka-broker0
    replicas: 1
    pod_label: kafka-pod
    pod_id: "0"
    image: wurstmeister/kafka
    container_port: 9092
    kafka_advertised_port: "9092"
    kafka_advertised_host_name:  "kafka-service"
    kafka_zookeeper_connect: zoo1:2181
    kafka_broker_id: "0"
    kafka_create_topics: testtopic:3:1

    service_name: kafka-service

zookeeper:
    container_name: zoo1
    deployment_name: zookeeper-deploy
    replicas: 1
    pod_label: zookeeper-1
    image: digitalwonderland/zookeeper
    container_port: 2181
    zookeeper_id: "1"
    zookeeper_server: zoo1

    service_name: zoo1
    client_port: 2181
    follower_port: 2888
    leader_port: 3888
